Add the sql script of the creation of the database
PRA-DEK/API pull request #3
Opened 2022-06-16 09:05 UTC by Arthur-Ponty

2022-06-16 09:08 UTC, john-btg approved these changes

2022-06-16 09:56 UTC, DarkKem requested changes

2022-06-16 09:56 UTC, DarkKem commented on script_sql/Etno_mysql_create.sql
> +CREATE TABLE `Birds` (
Mauvais nom met plutôt `Pigeon`

2022-06-23 08:51 UTC, DarkKem approved these changes

2022-06-23 08:55 UTC, merged